version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: semantic-auth-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: semantic_auth

volumes:
  mongodata:
