# fly.toml
app = "semantic-auth"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data/db"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[processes]]
  app = "/path/to/your/go/binary"

[[processes]]
  mongo = "mongod --dbpath /data/db --bind_ip_all"
